name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install recursive
      run: cargo install cargo-recursive
    - name: Check formatting
      run: cargo recursive fmt --verbose
    - name: Run tests
      run: cargo recursive test --verbose
